#!/usr/bin/env python3
"""Generate the signed-build XcodeGen spec from the canonical project.yml.

This eliminates the source-of-truth drift between `project.yml` (used by
`scripts/setup-screentime.sh` for unsigned simulator builds) and the
heredoc that `scripts/build_signed.sh` previously generated by hand for
TestFlight archives. Both signed and unsigned builds now derive from a
single committed XcodeGen spec.

The signed build differs from the simulator build only in the following
controlled ways, all of which this script applies as overlays on top of
the loaded `project.yml`:

  * Project `name` is suffixed with "Signed".
  * Source / package / Info.plist / entitlement paths are rewritten to be
    absolute (the signed `.xcodeproj` is generated to a sibling directory
    under DerivedData rather than `ScreenTimeExtensions/`).
  * Each target's `CODE_SIGN_*` settings are flipped from the simulator
    NO/empty values to YES + a Distribution identity, with optional
    manual `PROVISIONING_PROFILE_SPECIFIER`.
  * Per-target `CODE_SIGN_ENTITLEMENTS` is repointed at the
    `.Distribution.entitlements` variant of each target's entitlements
    file (the unsigned `.entitlements` variant strips Apple-managed
    keys the simulator can't fulfil).
  * `MARKETING_VERSION` and `CURRENT_PROJECT_VERSION` are overridden
    from the environment / TestFlight build number.
  * A `PrivacyInfo.xcprivacy` copy step is appended to the main app's
    `postBuildScripts` (required for App Store privacy nutrition labels
    on signed-build only — the unsigned simulator build doesn't need
    them).
  * The scheme is replaced by a single archive-focused scheme.
  * When `--extension-profiles-available no`, extension targets are
    removed (gated on FamilyControls entitlement approval — #201).

Any new top-level target added to `project.yml` is rejected unless it is
explicitly registered in `_TARGET_SIGNING_PROFILE` so the operator must
audit signing prerequisites for the new target.

Usage:
  signed_project_spec.py \
    --source project.yml --output out/signed.yml \
    --app-name EyePostureReminder \
    --package-path /abs/repo/root \
    --marketing-version 0.2.0 --build-number 202605181400 \
    --team-id ABCDEFGHIJ \
    --signing-style Manual --code-sign-identity 'Apple Distribution' \
    --signed-entitlements /abs/path/EyePostureReminder.Distribution.entitlements \
    --shield-config-entitlements /abs/path/ShieldConfigurationExtension.Distribution.entitlements \
    --device-activity-entitlements /abs/path/DeviceActivityMonitorExtension.Distribution.entitlements \
    --provisioning-profile 'EPR Distribution' \
    --extension-profiles-available no \
    --configuration Release
"""
from __future__ import annotations

import argparse
import os
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    sys.stderr.write(
        "signed_project_spec.py requires PyYAML. Install with: "
        "python3 -m pip install --user pyyaml\n"
    )
    raise SystemExit(1)


# Targets the signed build knows how to sign. Adding a new target to
# `project.yml` requires:
#   1. Adding an entry here that maps the target to its entitlements-path
#      CLI flag (None means "main app — uses --signed-entitlements").
#   2. Wiring the corresponding signing/profile CLI flag in
#      `scripts/build_signed.sh`.
# Drift between `project.yml` and this map fails loudly in `_assert_targets_known`.
_TARGET_SIGNING_PROFILE: dict[str, str | None] = {
    "EyePostureReminder": None,
    "ShieldConfigurationExtension": "shield_config_entitlements",
    "DeviceActivityMonitorExtension": "device_activity_entitlements",
}

_EXTENSION_TARGETS: tuple[str, ...] = (
    "ShieldConfigurationExtension",
    "DeviceActivityMonitorExtension",
)


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate signed-build XcodeGen spec from project.yml."
    )
    parser.add_argument("--source", required=True, help="Path to project.yml.")
    parser.add_argument("--output", required=True, help="Path to write merged spec.")
    parser.add_argument("--app-name", required=True)
    parser.add_argument(
        "--package-path",
        required=True,
        help="Absolute path to the repository root (Swift package).",
    )
    parser.add_argument("--marketing-version", required=True)
    parser.add_argument("--build-number", required=True)
    parser.add_argument("--team-id", default="")
    parser.add_argument(
        "--signing-style", choices=("Manual", "Automatic"), default="Manual"
    )
    parser.add_argument("--code-sign-identity", default="Apple Distribution")
    parser.add_argument("--signed-entitlements", required=True)
    parser.add_argument("--shield-config-entitlements", required=True)
    parser.add_argument("--device-activity-entitlements", required=True)
    parser.add_argument("--provisioning-profile", default="")
    parser.add_argument("--shield-config-profile", default="")
    parser.add_argument("--device-activity-profile", default="")
    parser.add_argument(
        "--extension-profiles-available",
        choices=("yes", "no"),
        default="no",
        help="Include extension targets in the signed archive (gated on #201).",
    )
    parser.add_argument("--configuration", default="Release")
    return parser.parse_args(argv)


def _assert_targets_known(spec: dict) -> None:
    """Fail loudly if `project.yml` contains a target the signed build
    doesn't know how to sign. Forces explicit registration.
    """
    targets = spec.get("targets", {}) or {}
    unknown = sorted(set(targets) - set(_TARGET_SIGNING_PROFILE))
    if unknown:
        raise SystemExit(
            "signed_project_spec: project.yml contains unsigned target(s) "
            f"{unknown}. Register each in `_TARGET_SIGNING_PROFILE` and wire "
            "a signing-profile CLI flag in scripts/build_signed.sh before "
            "running the signed build (issue #929 covers this drift gate)."
        )

    missing = sorted(set(_TARGET_SIGNING_PROFILE) - set(targets))
    if missing:
        raise SystemExit(
            "signed_project_spec: signing map references target(s) "
            f"{missing} that no longer exist in project.yml. Drop them "
            "from `_TARGET_SIGNING_PROFILE` in this script."
        )


def _abs_under(base: str, path: str) -> str:
    """Resolve `path` to an absolute path using `base` as the join root."""
    if os.path.isabs(path):
        return os.path.normpath(path)
    return os.path.normpath(os.path.join(base, path))


def _absolutize_target_paths(
    spec: dict, *, project_yml_dir: str, extensions_xcodeproj_dir: str
) -> None:
    """Rewrite relative paths in the loaded spec to absolute paths.

    XcodeGen resolves paths differently depending on field:

      * `targets.*.sources[].path` is resolved relative to the **spec
        file's directory**.
      * `packages.*.path` is stored verbatim in the generated .xcodeproj
        and resolved by Xcode/SwiftPM relative to the **.xcodeproj's
        parent directory**.
      * Build settings such as `INFOPLIST_FILE` and `CODE_SIGN_ENTITLEMENTS`
        are baked into the pbxproj verbatim and resolved by Xcode
        relative to the **.xcodeproj's parent directory** at build time.

    The committed `project.yml` is consumed by `setup-screentime.sh`,
    which generates `ScreenTimeExtensions/EyePostureReminderExtensions.xcodeproj`.
    All `..`-prefixed paths in project.yml therefore assume the
    .xcodeproj sits at `ScreenTimeExtensions/`. The signed build emits
    the .xcodeproj elsewhere (DerivedData), so this function rewrites
    every path the signed build cares about to an absolute path —
    XcodeGen + Xcode handle absolute paths transparently in all
    contexts above.
    """
    packages = spec.get("packages") or {}
    for pkg in packages.values():
        if isinstance(pkg, dict) and "path" in pkg:
            pkg["path"] = _abs_under(extensions_xcodeproj_dir, pkg["path"])

    for target in (spec.get("targets") or {}).values():
        sources = target.get("sources") or []
        rewritten_sources = []
        for source in sources:
            if isinstance(source, dict) and "path" in source:
                source["path"] = _abs_under(project_yml_dir, source["path"])
                rewritten_sources.append(source)
            elif isinstance(source, str):
                rewritten_sources.append(_abs_under(project_yml_dir, source))
            else:
                rewritten_sources.append(source)
        if sources:
            target["sources"] = rewritten_sources

        settings = (target.get("settings") or {}).get("base") or {}
        for key in ("INFOPLIST_FILE", "CODE_SIGN_ENTITLEMENTS"):
            if key in settings:
                settings[key] = _abs_under(extensions_xcodeproj_dir, settings[key])


def _apply_signing(
    spec: dict, *, args: argparse.Namespace, profile_map: dict[str, str]
) -> None:
    """Apply Distribution signing overrides per target.

    `project.yml` ships simulator-friendly empty CODE_SIGN_IDENTITY /
    NO CODE_SIGNING_* values. The signed build replaces them with a
    Distribution identity, optionally pinned to a manual provisioning
    profile, and re-points entitlements at the `.Distribution` variant.
    """
    for target_name, target in (spec.get("targets") or {}).items():
        settings = target.setdefault("settings", {}).setdefault("base", {})
        settings["CODE_SIGN_IDENTITY"] = args.code_sign_identity
        settings["CODE_SIGNING_ALLOWED"] = "YES"
        settings["CODE_SIGNING_REQUIRED"] = "YES"
        settings["CODE_SIGN_STYLE"] = args.signing_style
        if args.team_id:
            settings["DEVELOPMENT_TEAM"] = args.team_id
        settings["MARKETING_VERSION"] = args.marketing_version
        settings["CURRENT_PROJECT_VERSION"] = args.build_number

        # Repoint entitlements at the .Distribution variant. The mapping
        # is target-keyed so a target without a Distribution entitlement
        # file falls through and the operator gets the error from
        # require_signed_entitlements in build_signed.sh.
        if target_name == args.app_name:
            settings["CODE_SIGN_ENTITLEMENTS"] = args.signed_entitlements
            profile = args.provisioning_profile
        else:
            entitlements_path = profile_map.get(target_name)
            if entitlements_path:
                settings["CODE_SIGN_ENTITLEMENTS"] = entitlements_path
            profile = (
                args.shield_config_profile
                if target_name == "ShieldConfigurationExtension"
                else args.device_activity_profile
            )

        if args.signing_style == "Manual" and profile:
            settings["PROVISIONING_PROFILE_SPECIFIER"] = profile


def _strip_unused_extensions(spec: dict, *, app_name: str) -> None:
    """Drop extension targets and the app's dependencies on them when
    extension provisioning profiles are unavailable (the current
    TestFlight reality pre-#201)."""
    targets = spec.get("targets") or {}
    for ext in _EXTENSION_TARGETS:
        targets.pop(ext, None)

    app = targets.get(app_name)
    if app and "dependencies" in app:
        app["dependencies"] = [
            dep
            for dep in app["dependencies"]
            if not (
                isinstance(dep, dict)
                and dep.get("target") in _EXTENSION_TARGETS
            )
        ]


def _append_privacy_copy_step(spec: dict, *, app_name: str, package_path: str) -> None:
    """Append `PrivacyInfo.xcprivacy` copy to the main app's post-build
    scripts. Required for App Store privacy nutrition labels (only the
    signed archive needs this — the simulator build short-circuits)."""
    app = (spec.get("targets") or {}).get(app_name) or {}
    scripts = app.setdefault("postBuildScripts", [])

    privacy_src = os.path.join(package_path, "EyePostureReminder", "PrivacyInfo.xcprivacy")
    privacy_step_name = "Embed PrivacyInfo.xcprivacy"
    if any(step.get("name") == privacy_step_name for step in scripts):
        return

    scripts.append(
        {
            "name": privacy_step_name,
            "basedOnDependencyAnalysis": False,
            "script": (
                "set -e\n"
                f'PRIVACY_SRC="{privacy_src}"\n'
                'PRIVACY_DST="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_FOLDER_PATH}/PrivacyInfo.xcprivacy"\n'
                'if [ -f "$PRIVACY_SRC" ]; then\n'
                '  cp "$PRIVACY_SRC" "$PRIVACY_DST"\n'
                "fi\n"
            ),
        }
    )


def _replace_schemes(spec: dict, *, app_name: str, configuration: str) -> None:
    """Replace the project.yml scheme set with a single archive scheme."""
    spec["schemes"] = {
        app_name: {
            "build": {"targets": {app_name: ["run", "archive"]}},
            "archive": {"config": configuration},
        }
    }


def main(argv: list[str]) -> int:
    args = _parse_args(argv)

    project_yml_dir = os.path.dirname(os.path.abspath(args.source))
    extensions_xcodeproj_dir = os.path.join(args.package_path, "ScreenTimeExtensions")

    with open(args.source, "r", encoding="utf-8") as handle:
        spec = yaml.safe_load(handle)
    if not isinstance(spec, dict):
        raise SystemExit(f"signed_project_spec: {args.source} is not a YAML mapping.")

    _assert_targets_known(spec)

    spec["name"] = f"{args.app_name}Signed"
    _absolutize_target_paths(
        spec,
        project_yml_dir=project_yml_dir,
        extensions_xcodeproj_dir=extensions_xcodeproj_dir,
    )

    if args.extension_profiles_available == "no":
        _strip_unused_extensions(spec, app_name=args.app_name)

    profile_map = {
        "ShieldConfigurationExtension": args.shield_config_entitlements,
        "DeviceActivityMonitorExtension": args.device_activity_entitlements,
    }
    _apply_signing(spec, args=args, profile_map=profile_map)

    _append_privacy_copy_step(
        spec, app_name=args.app_name, package_path=args.package_path
    )

    _replace_schemes(
        spec, app_name=args.app_name, configuration=args.configuration
    )

    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(
            "# AUTO-GENERATED by scripts/lib/signed_project_spec.py from project.yml.\n"
            "# Do not edit by hand — the source of truth is project.yml + the\n"
            "# signing overrides applied by scripts/build_signed.sh (issue #929).\n"
        )
        yaml.safe_dump(spec, handle, sort_keys=False, default_flow_style=False)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
